services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      LIVEKIT_KEYS: "devkey: secret"
      LIVEKIT_WEBHOOK_URLS: ""
      LIVEKIT_LOG_LEVEL: "info"
    command: --dev --node-ip=127.0.0.1
    networks:
      - filmroom

networks:
  filmroom:
    driver: bridge