# Nixpacks configuration for monorepo
# This configures both Node.js and Python environments

[phases.setup]
# Install both Node.js and Python packages
nixPkgs = ["nodejs_20", "python311", "postgresql"]
aptPkgs = ["build-essential", "libpq-dev"]

[phases.install]
# Install dependencies for both Node and Python
cmds = [
    "corepack enable",
    "corepack prepare pnpm@9.15.2 --activate", 
    "pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]

[start]
# This will be overridden by service-specific commands in flightcontrol.json
cmd = "echo 'Start command should be specified in flightcontrol.json'"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "20"