"""Add recording fields to session model

Revision ID: 923089c85bcd
Revises: f46ea92fed49
Create Date: 2025-09-03 09:00:26.045538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923089c85bcd'
down_revision: Union[str, Sequence[str], None] = 'f46ea92fed49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('recording_s3_key', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('recording_egress_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('recording_status', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('recording_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('recording_size_bytes', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('recording_started_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('recording_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'recording_completed_at')
    op.drop_column('sessions', 'recording_started_at')
    op.drop_column('sessions', 'recording_size_bytes')
    op.drop_column('sessions', 'recording_duration_seconds')
    op.drop_column('sessions', 'recording_status')
    op.drop_column('sessions', 'recording_egress_id')
    op.drop_column('sessions', 'recording_s3_key')
    # ### end Alembic commands ###
