"""Initial database schema

Revision ID: f389418cae43
Revises: 
Create Date: 2025-08-27 17:26:13.824109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f389418cae43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('COACH', 'CLIENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('coaching_goals', sa.Text(), nullable=True),
    sa.Column('background_info', sa.Text(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('initial_assessment', sa.Text(), nullable=True),
    sa.Column('current_challenges', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=True),
    sa.Column('last_session_date', sa.DateTime(), nullable=True),
    sa.Column('next_session_date', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='sessionstatus'), nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('room_sid', sa.String(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('actual_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cal_booking_id', sa.String(), nullable=True),
    sa.Column('cal_event_type_id', sa.String(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_cal_booking_id'), 'sessions', ['cal_booking_id'], unique=False)
    op.create_index(op.f('ix_sessions_room_name'), 'sessions', ['room_name'], unique=True)
    op.create_table('client_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_profile_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('overall_sentiment', sa.String(), nullable=True),
    sa.Column('sentiment_scores', sa.JSON(), nullable=True),
    sa.Column('emotional_moments', sa.JSON(), nullable=True),
    sa.Column('goals_discussed', sa.JSON(), nullable=True),
    sa.Column('progress_indicators', sa.JSON(), nullable=True),
    sa.Column('challenges_identified', sa.JSON(), nullable=True),
    sa.Column('breakthroughs', sa.JSON(), nullable=True),
    sa.Column('suggested_followups', sa.JSON(), nullable=True),
    sa.Column('client_engagement_score', sa.Float(), nullable=True),
    sa.Column('session_effectiveness_score', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_transcriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('raw_transcription', sa.Text(), nullable=False),
    sa.Column('formatted_transcription', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcription_engine', sa.String(), nullable=True),
    sa.Column('speakers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_transcriptions')
    op.drop_table('session_insights')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_sessions_room_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_cal_booking_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
