"""Add Cal.com integration fields

Revision ID: f46ea92fed49
Revises: c4de5cf92f0d
Create Date: 2025-09-03 08:39:20.193952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46ea92fed49'
down_revision: Union[str, Sequence[str], None] = 'c4de5cf92f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cal_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cal_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cal_event_type_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cal_booking_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cal_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cal_booking_url')
    op.drop_column('users', 'cal_event_type_id')
    op.drop_column('users', 'cal_user_id')
    op.drop_column('users', 'cal_username')
    # ### end Alembic commands ###
